import { VsNavigation } from '@vertical/types';

export const navigation: VsNavigation[] = [
  {
    level: 1,
    id: 'products',
    title: 'Products',
    translate: 'NAV.PRODUCTS.TITLE',
    type: 'collapsable',
    icon: 'mail',
    open: true,
    selected: false,

    children: [
      {
        level: 2,
        id: 'manage-products',
        title: 'Manage Products',
        type: 'item',
        url: '/products/manage-products',
        exactMatch: false,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'manage-images',
        title: 'Manage Images',
        type: 'item',
        url: '/products/manage-images',
        exactMatch: false,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'manage-categories',
        title: 'Manage Categories',
        type: 'item',
        url: '/products/manage-categories',
        exactMatch: false,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'batch-upload',
        title: 'Batch Upload',
        type: 'item',
        url: '/products/batch-upload',
        exactMatch: false,
        open: false,
        selected: false,
      },
    ],
  },
  {
    level: 1,
    id: 'orders',
    title: 'Orders',
    translate: 'NAV.ORDERS.TITLE',
    type: 'collapsable',
    icon: 'mail',
    open: false,
    selected: false,
    children: [
      {
        level: 2,
        id: 'manage-orders',
        title: 'Manage Orders',
        type: 'item',
        url: '/orders/manage-orders',
        exactMatch: true,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'manage-return-orders',
        title: 'Manage Return Orders',
        type: 'item',
        url: '/orders/manage-return-orders',
        exactMatch: true,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'manage-reviews',
        title: 'Manage Reviews',
        type: 'item',
        url: '/orders/manage-reviews',
        exactMatch: true,
        open: false,
        selected: false,
      },
    ],
  },
  {
    level: 1,
    id: 'promotions',
    title: 'Promotions',
    translate: 'NAV.PROMOTIONS.TITLE',
    type: 'collapsable',
    icon: 'mail',
    open: false,
    selected: false,
    children: [
      {
        level: 2,
        id: 'campaign-management',
        title: 'Campaign Management',
        type: 'item',
        url: '/promotions/campaign-management',
        exactMatch: true,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'seller-voucher',
        title: 'Seller Voucher',
        type: 'item',
        url: '/promotions/seller-voucher',
        exactMatch: true,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'free-shipping',
        title: 'Free Shipping',
        type: 'item',
        url: '/promotions/free-shipping',
        exactMatch: true,
        open: false,
        selected: false,
      },
    ],
  },
  {
    level: 1,
    id: 'finance',
    title: 'Finance',
    translate: 'NAV.FINANCE.TITLE',
    type: 'collapsable',
    icon: 'mail',
    open: false,
    selected: false,
    children: [
      {
        level: 2,
        id: 'account-statements',
        title: 'Account Statements',
        type: 'item',
        url: '/finance/account-statements',
        exactMatch: true,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'order-overview',
        title: 'Order Overview',
        type: 'item',
        url: '/finance/order-overview',
        exactMatch: true,
        open: false,
        selected: false,
      },
      {
        level: 2,
        id: 'transaction-overview',
        title: 'Transaction Overview',
        type: 'item',
        url: '/finance/transaction-overview',
        exactMatch: true,
        open: false,
        selected: false,
      },
    ],
  },
  {
    level: 1,
    id: 'store',
    title: 'Store',
    translate: 'NAV.STORE.TITLE',
    type: 'item',
    icon: 'mail',
    url: '/store/manage-store',
    open: false,
    selected: false,
  },
];
